# This is a basic workflow to help you get started with Actions

name: Build and push helm yq3

# Controls when the workflow will run
on:
  push:
    branches: [ master ]
  schedule:
    - cron:  "30 5 * * *"
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build the image
        run: |
          YQ_VERSION=yq-3.3.1
          docker build alpine-helm-yq3/ --tag ${{ secrets.DOCKER_HUB_USERNAME }}/alpine-helm-yq:${YQ_VERSION}

      - name: Push the image
        run: |
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/alpine-helm-yq --all-tags
