# This is a basic workflow to help you get started with Actions

name: Build and push : Alpine - Google cloud sdk + kubectl

# Controls when the workflow will run
on:
  push:
    branches: [ master ]
  schedule:
    - cron:  "30 5 * * *"
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build the image
        run: |
          docker build alpine-google-sdk-kubectl/ --tag ${{ secrets.DOCKER_HUB_USERNAME }}/alpine-google-sdk-kubectl:latest
          GOOGLE_SDK_VERSION=371.0.0
          docker build alpine-google-sdk-kubectl/ --tag ${{ secrets.DOCKER_HUB_USERNAME }}/alpine-google-sdk-kubectl:${GOOGLE_SDK_VERSION}

      - name: Push the image
        run: |
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/alpine-google-sdk-kubectl --all-tags
