# This is a basic workflow to help you get started with Actions

name: Build and push : Alpine - yq

# Controls when the workflow will run
on:
  push:
    branches: [ master ]
  schedule:
    - cron:  "30 5 * * *"
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build the image
        run: |
          docker build alpine-yq/ --tag ${{ secrets.DOCKER_HUB_USERNAME }}/alpine-yq:latest
          YQ_VERSION=$(docker run ${{ secrets.DOCKER_HUB_USERNAME }}/alpine-yq:latest yq --version | cut -d " " -f 4)
          docker build alpine-yq/ --tag ${{ secrets.DOCKER_HUB_USERNAME }}/alpine-yq:${YQ_VERSION}

      - name: Push the image
        run: |
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/alpine-yq --all-tags
